# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d2183da01a295efc4c067acfcc3ec69a71dc3ce396a77bc707c566fe55f8475f09eaaa791232b1ea5abe7d6350fb5e5b11e0ec0ce1e2403b22de7b298450828

test:
  secret_key_base: 8f634c1ffb40e976a2ad2dbbe5624eed6ba2cdbd1f1a4fd9b82c662f582e403f08aee0dc3acbe19993aba92e80a057287c6d17ce74001f0c7468985ad65c736f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
